name: Docker CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ericnorwing/dotaproject

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Docker (if not available)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Check Docker version
      - name: Check Docker version
        run: docker --version

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into the GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: DotaProject/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Debugging: List Docker images
      - name: List Docker images
        run: docker images

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d \
            -p 8080:8080 \
            -p 8081:8081 \
            -e ConnectionStrings__DefaultConnection=${{ secrets.AZURE_SQL_CONNECTION_STRING }} \
            -e JwtSettings__PrivateKey=${{ secrets.JWTPRIVATEKEY }} \
            -e JwtSettings__PublicKey=${{ secrets.JWTPUBLICKEY }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
